// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxu9R1pr4SgA1pcA3KQ62Ithfa7n04YA',
    appId: '1:681885628519:web:b432b7880a9810a310bcc2',
    messagingSenderId: '681885628519',
    projectId: 'fiba-quiz',
    authDomain: 'fiba-quiz.firebaseapp.com',
    storageBucket: 'fiba-quiz.appspot.com',
    measurementId: 'G-WLWMEEG9HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPExAB2hCX6acFGX4IZU14_TNuminRYAY',
    appId: '1:681885628519:android:6a5e7a50b5759da710bcc2',
    messagingSenderId: '681885628519',
    projectId: 'fiba-quiz',
    storageBucket: 'fiba-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzUgm-M6uhlqjPpNZjKqyUABHKPOFlkhE',
    appId: '1:681885628519:ios:c4a265adba84710010bcc2',
    messagingSenderId: '681885628519',
    projectId: 'fiba-quiz',
    storageBucket: 'fiba-quiz.appspot.com',
    iosClientId: '681885628519-u8ddk97i3g2j3qsu2tmq9a6laru94j7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fibaQuiz',
  );
}
